name: PR tests

on:
  pull_request:
    types: [ready_for_review]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  alltests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run all tests
        run: make alltests
